- name: Kubernetes Step 2 - Create Kubernetes utils (Waiting Flannel and kube-dns Pod is Running)
  hosts: master
  gather_facts: yes
  remote_user: pi
  become: true
  vars_files:
    - config.yml

  roles:
  - utils