- name: Reset Kubernetes installation
  shell: "kubeadm reset"

- name: Disable swap
  shell: "swapoff --all"

- name: Initialize Kubernetes cluster for ARM with flannel support
  shell: "kubeadm init --token {{token}} --pod-network-cidr={{cidr}} --token-ttl 0"
  register: out

- debug: var=out.stdout_lines

- name: Install Networking Pods (kube-flannel)
  shell: "curl -sSL https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml | sed 's/amd64/arm/g' | kubectl apply -f -"
  register: out

- debug: var=out.stdout_lines

- name: Delete old .kube folder
  shell: "rm -rf ~/.kube"
  ignore_error: yes

- name: Create .kube folder
  shell: "mkdir ~/.kube"

- name: Copy default Cluster Configuration file
  shell: "cp /etc/kubernetes/admin.conf ~/.kube/config"

- name: Set permisson to config file
  shell: "chown $(id -u):$(id -g) ~/.kube/config"