version: '2'

services:
  haproxy:
    image: hypriot/rpi-haproxy
    volumes:
      - $PWD:/haproxy-override
    ports:
    - "80:80"
    - "843:843"
    - "1936:1936"
    network_mode: "host"

  redis:
    image: mangoraft/redis-arm
    environment:
      - REDIS_PASS=abc123
    ports:
      - "6379:6379"