- name: Reset Kubernetes installation
  shell: "kubeadm reset"

- name: Disable swap
  shell: "swapoff --all"

- name: Initialize Kubernetes cluster for ARM with flannel support
  shell: "kubeadm init --token={{token}} --pod-network-cidr={{cidr}}"
  register: out

- debug: var=out.stdout_lines

- name: Delete old .kube folder
  shell: "rm -rf ~/.kube"
  ignore_error: yes

- name: Create .kube folder
  shell: "mkdir ~/.kube"

- name: Copy default Cluster Configuration file
  shell: "cp /etc/kubernetes/admin.conf ~/.kube/config"

- name: Set permisson to config file
  shell: "chown $(id -u):$(id -g) ~/.kube/config"