- name: Reset Kubernetes Installation
  hosts: pis
  gather_facts: yes
  remote_user: pirate
  become: true
  become_method: sudo
  vars_files:
    - config.yml

  roles:
    - reset
    - reset-iptables